name: bwu_dev_server
version: 0.1.0
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: An HTTP server for Dart client development.
homepage: https://github.com/bwu-dart/bwu_dev_server
environment:
  sdk: '>=1.10.0 <2.0.0'

executables:
  devserver:

dependencies:
  package_config: '^0.1.3'
#  path: '^1.3.5'
  shelf: '^0.6.4+1'
  shelf_cors: '^0.2.1'
  shelf_route: '^0.14.0'
  shelf_static: '^0.2.3+1'
  unscripted: '^0.6.1+1'

dev_dependencies:
  bwu_grinder_tasks: '^0.1.0'
  grinder: '^0.7.2'
  test: ^0.12.5+1

#transformers:
#- web_components:
#    entry_points:
#    - test/bwu_bind_html_test.html
#    - test/default_validator_test.html
#- reflectable:
#    entry_points:
#    - test/bwu_bind_html_test.dart
#    - test/default_validator_test.dart
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart
#- $dart2js:
#    $include: '**/*.bootstrap.initialize.dart'
#    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']

